### ISSUE TITLE
Google Font Proxy

### ISSUE THREAD

**Issue by nickbe** [microweber/microweber#1053]
We've just saw the setting "Google Font Proxy". How exactly does it work? 
There's seems to be no documentation or any other GitHub Issue regarding this.

According to current law here it's illegal to load google fonts from an american server.
So without this feature or modifying the licensed big theme from the beginning we can't use it.

Cheers

**Comment by peter-mw** [comment]
Hi, the google fonts proxy loads from the domain google-fonts.microweberapi.com , this server is hosted in Hetzner Germany 

For example 

https://google-fonts.microweberapi.com/css?family=Varela:300italic,400italic,600italic,700italic,800italic,400,600,800,700,300&subset=latin,cyrillic-ext,greek-ext,greek,vietnamese,latin-ext,cyrillic

Is proxy to 

https://fonts.googleapis.com/css?family=Varela:300italic,400italic,600italic,700italic,800italic,400,600,800,700,300&subset=latin,cyrillic-ext,greek-ext,greek,vietnamese,latin-ext,cyrillic


This is experimental setting and its not implemented on all places yet .

Given your feedback we will add option to download fonts locally and serve them from the website address instead of remote proxy.

**Comment by nickbe** [comment]
Thanks for the information.  If you take a look at this list of used external resources then there's more which must be able to disable to make a website conform to current laws an regulations.

![image](https://github.com/microweber/microweber/assets/10890765/2d5e3aaf-0316-4964-98ad-a5adf35e078d)

Here the basic rule is that nothin might be loaded from outside the EU at all. 
Moreover it is strongly advisable to be able to prevent ALL external sources no matter what.

So it should be possible to make microweber load everything from local only.

**Comment by peter-mw** [comment]
We made Google fonts to be download at the local site. 

Releasing it with version 2.0.8 soon

**Comment by nickbe** [comment]
Ok thanks. Good to hear
