### ISSUE TITLE
language setting

### ISSUE THREAD

**Issue by stoensin** [microweber/microweber#280]
#when i setting the language to chinese,  next time i open the dashbord it back to the setting before i changed it

**Comment by peter-mw** [comment]
hi, is the language back to English again?

**Comment by stoensin** [comment]
1.yes，the language back to English again
2.i change the language in dashbord->settings->language,also i change it in the zh-cn.json

**Comment by peter-mw** [comment]
Hello,

I see, this is because the language is not translated. 

The currently translated languages are https://github.com/microweber/microweber/tree/1.0/userfiles/modules/microweber/language

If you want to translate to Chinese, just edit the entries there and they will be saved automatically 

This will make new file in the folder `userfiles/language`

If you want you can submit your translation to us, so we can add it in the core

**Comment by stoensin** [comment]
Very strange,even i had tranlated the language to chinese,the file in userfile/language/zh-cn.json always back to english again an again.

**Comment by peter-mw** [comment]
Hi yes, this is because it was broken. I just fixed it, can you replace your file with this 

https://github.com/microweber/microweber/blob/1.0/userfiles/modules/microweber/language/zh-cn.json

**Comment by stoensin** [comment]
:+1:  it work now
