### ISSUE TITLE
Microweber the base of a shopify like ?

### ISSUE THREAD

**Issue by chrigui** [microweber/microweber#379]
hello,
First thank you for sharing such an amazing platform,
i was wondering if Microweber is a start for a shopify or multi commerce saas platform ?
if yes, can you please let me know if the github source code has everything your Hosted solution offers ?

how is the license work ?
is the auto user account setup (new instance) automated or it has to happen manually ? 
the super admin can setup plans and manage billing ?

thank you

**Comment by peter-mw** [comment]
Hello,

We use exactly the same version in our site and all users sites as here in gihub

If you use the license you will be able to change the logos and the system's name.

For the user account creation we use external systems. 

The process is on 2 parts

1) We use https://www.whmcs.com/ 's software to define user plans
2) The WHMCS software is connected to cPanel , where the Microweber site is installed automatically with [those scripts](https://github.com/microweber/microweber-hosting-scripts)



You will need to buy separate licenses for WHMCS and Cpanel from them, in order to use this process.
If you want you can setup Virtualmin + WHMCS which also works.  


Hope this information helps.

**Comment by chrigui** [comment]
Thank you Peter for your reply,
i think you have explained it properly, i will be contacting you privately for some custom work like Customer Loyalty points, Service booking module (for restaurants and spas) and few more in mind.

Cheers.
