### ISSUE TITLE
Is it possible to set redirect location after login as admin

### ISSUE THREAD

**Issue by kitlung** [microweber/microweber#504]
Is it possible to redirect to dashboard after login as admin?

Or is it possible to start live edit mode after login as admin?

**Comment by peter-mw** [comment]
for login you can do something like that 

using GET or POST request

This will login only http://example.com/api/user_login?username=user&password=pass

This will login and redirect: http://example.com/api/user_login?username=user&password=pass&redirect=http%3A%2F%2Fexample.com%2Fadmin

**Comment by Ezyweb-uk** [comment]
Is your version redirecting to the website home page after login instead of the admin dashboard? I had a similar issue recently, you might want to check your code in `userfiles\modules\users\login\index.php` around line 49, I changed the following line:
`window.location.href ='<?php print site_url(); ?>';`
to
`window.location.reload();`
