### ISSUE TITLE
Host Header Injection

### ISSUE THREAD

**Issue by Hades484** [microweber/microweber#717]
Host header injection vulnerability found on microweber CMS, Using this attack, a malicious user can poison the web cache or arbitrary user re-direction.
![image](https://user-images.githubusercontent.com/78723738/107222259-b1e2a480-6a3a-11eb-8d40-b5aa2d14aed2.png)
Burp suite
![image](https://user-images.githubusercontent.com/78723738/107221868-37198980-6a3a-11eb-8d9c-f6ff90803acd.png)

**Comment by peter-mw** [comment]
Hello,

This issue is because the web server name is not properly set on the web server config. 

This is not in the scope of our project as in many cases you may wish to run the software behind reverse proxy, such as Cloudflare. 

This is issue is related to the web server configuration. 

To prevent this issue please set the server name in the web server config. 

https://httpd.apache.org/docs/2.4/vhosts/examples.html

Also the cache is set on each domain. For example if you have multi domain install the domain name is taken into account for the cache. 

As you can see on our web server this issue is not present as the server is properly configured

`curl http://demo.microweber.org/ -H "host:www.google.com"`

Closing this issue as WONTFIX
