### ISSUE TITLE
Gallery (Grid) - Masnonry

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#831]
Guys, when uploading images to Carousel Grid Gallery (the one with "Your Pretty Gallery" text title) it sometimes displays thumbnails in Mansonry and sometimes in classic grid layout, how can I choose which to display?

I would need it like so:
![Screenshot-gallery](https://user-images.githubusercontent.com/19394068/159001925-90a47ed4-1c99-4462-a9f5-22f607666d32.png)

**Comment by RogerAntonio** [comment]
Sounds like you're talking about it showing another template from time to time.
You should be able to swap templates by opening the module settings (hover over the masonry, click on edit, then select the templates tab).

Example of templates for the testimonial module:
![image](https://user-images.githubusercontent.com/5510591/159022223-c0de3882-3575-4f8d-be9f-1b7c011dd29b.png)

If this is not what you meant, please explain a little better what your issue is?

It could also just be another layout, I'm not sure. I don't use New-world

**Comment by gokkstudio** [comment]
Thank you @RogerAntonio this is the way.
