### ISSUE TITLE
Cloning a Layout not cloning content

### ISSUE THREAD

**Issue by gokkstudio** [microweber/microweber#849]
Hi, 
cloning layout/section doesn't clone the content inside, is this intended or?

Latest version: 1.2.13

**Comment by gokkstudio** [comment]
Any thought on this?

**Comment by RogerAntonio** [comment]
Cloning only clones the layout, not the content.
A way around this is to make a preset of the layout.
Go into the layout's settings, click on the triangle on the right of the title bar and select Presets.
Create a new preset.
Now clone the layout and do exactly the same, except use the preset instead of creating it.

**Comment by gokkstudio** [comment]
Oh.. I see. Well, that's not bad at all.
As always, thank you @RogerAntonio
